// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackendSetMinHeight(arg1) {
  return window['go']['main']['App']['BackendSetMinHeight'](arg1);
}

export function BackendSetMinSize(arg1) {
  return window['go']['main']['App']['BackendSetMinSize'](arg1);
}

export function BackendSetMinWidth(arg1) {
  return window['go']['main']['App']['BackendSetMinWidth'](arg1);
}

export function BackendSetMoveOrCopy(arg1) {
  return window['go']['main']['App']['BackendSetMoveOrCopy'](arg1);
}

export function BackendSetNamingConvention(arg1) {
  return window['go']['main']['App']['BackendSetNamingConvention'](arg1);
}

export function BackendSetVerifyResults(arg1) {
  return window['go']['main']['App']['BackendSetVerifyResults'](arg1);
}

export function ClearStartDirectories() {
  return window['go']['main']['App']['ClearStartDirectories']();
}

export function GetExamplePathSubstitution(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetExamplePathSubstitution'](arg1, arg2, arg3);
}

export function OpenHostLocation(arg1) {
  return window['go']['main']['App']['OpenHostLocation'](arg1);
}

export function ProcessImages() {
  return window['go']['main']['App']['ProcessImages']();
}

export function RemoveStartDirectory(arg1) {
  return window['go']['main']['App']['RemoveStartDirectory'](arg1);
}

export function ResetEverything() {
  return window['go']['main']['App']['ResetEverything']();
}

export function SelectDestinationDirectory() {
  return window['go']['main']['App']['SelectDestinationDirectory']();
}

export function SelectStartDirectories() {
  return window['go']['main']['App']['SelectStartDirectories']();
}

export function VerifyRelocation() {
  return window['go']['main']['App']['VerifyRelocation']();
}
