// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BackendSetMinHeight(arg1:number):Promise<void>;

export function BackendSetMinSize(arg1:number):Promise<void>;

export function BackendSetMinWidth(arg1:number):Promise<void>;

export function BackendSetMoveOrCopy(arg1:string):Promise<void>;

export function BackendSetNamingConvention(arg1:string):Promise<void>;

export function BackendSetVerifyResults(arg1:boolean):Promise<void>;

export function ClearStartDirectories():Promise<Array<string>>;

export function GetExamplePathSubstitution(arg1:string,arg2:main.ImageMetadata,arg3:string):Promise<main.ExampleSubstitution>;

export function OpenHostLocation(arg1:string):Promise<void>;

export function ProcessImages():Promise<void>;

export function RemoveStartDirectory(arg1:string):Promise<Array<string>>;

export function ResetEverything():Promise<void>;

export function SelectDestinationDirectory():Promise<string>;

export function SelectStartDirectories():Promise<Array<string>>;

export function VerifyRelocation():Promise<void>;
